name: data_drift_pipeline
version: "0.1.3"
shim_version: "2.9.4"

inputs:
  baseline:
    type: file
  new_data:
    type: file
  prob_col:
    type: string
    default: probability
  prob_prefix:
    type: string
    default: "prob-"
  js_high:
    type: float
    default: 0.04
  js_moderate:
    type: float
    default: 0.02
  psi_high:
    type: float
    default: 0.25
  psi_moderate:
    type: float
    default: 0.10

graph:
  drift_analysis_stage:
    service:
      actor:
        repo: https://github.com/phillipgreville/data_drift_pipeline.git@cc9ca5a5beeba07e4a3d5acdecb37dda7b2728b5
        path: actors.drift_analysis:run_drift_analysis
    tasks:
      run_drift_analysis:
        inputs:
          baseline: $$baseline
          new_data: $$new_data
          prob_col: $$prob_col
          prob_prefix: $$prob_prefix
          js_high: $$js_high
          js_moderate: $$js_moderate
          psi_high: $$psi_high
          psi_moderate: $$psi_moderate
